---
title: "solarpvtest"
format: html
---

Exploring and testing the solar photovoltaic model.

Load libraries
```{r}
library(tidyverse)
library(here)
```

Load data
```{r}
load(file = (here("Data", "sierraczosolar.rda")))
```

run model with sierra data
```{r}
solarpv(area = 0.1, 
        solar = sierraczosolar,
        eff = 0.6, clr = "green", eunit = "kW", g = FALSE)
```

```{r}
eff <- rnorm(mean = 0.6, sd = 0.1, n = 20)

site2 <- eff %>% map(~ solarpv(area = 0.1, 
                               solar = sierraczosolar, clr = "green",
                               eunit = "kWhr", g = FALSE, etype = "direct", 
                               eff = .x))

site2[[18]]$mean
```
```{r}
tmp <- map_dfr(site2, `[`, c("annual"))

site2df <- data.frame(year = tmp$annual$year, elect = tmp$annual$elect)
```

```{r}
thresh_test <- rnorm(mean = 10000, sd = 2000, n = 20)

test4 <- thresh_test %>% map(~ solarpv(area = 0.1, 
                               solar = sierraczosolar, clr = "green",
                               eunit = "kWhr", g = FALSE, etype = "direct", 
                               ethresh = .x))
```

